version: '3.7'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
